version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn bloodbankmanagement.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    # Remove or comment out this port mapping since nginx will handle external access
    # ports:
    #   - "8000:8000" 
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums --encoding=UTF8 --locale=C
      - TZ=UTC
      - PGTZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8080:80"  # Change from 8000:80 to 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data: